### ISSUE TITLE
Pls help why it is giving me this?

### ISSUE THREAD

**Issue by Yessicool** [efenatuyo/discord-nuke-bot#6]
![Screenshot_٢٠٢٤٠٩٢٩-١٩٠١٢٣](https://github.com/user-attachments/assets/26578ea8-736b-4e88-8e7c-936e29679313)

**Comment by Bueezi** [comment]
Hi Yesiscool,

Thank you for reporting this issue. While analyzing the screenshot you provided, it came to our team's attention that you are running AVG Antivirus on your Android device. Our team has since become concerned about your mental health. Please leave our GitHub and never come back!

Sincerely,
Bueezi
Head Moderator
